### ISSUE TITLE
Unable to Login : ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by AhSem** [jakiron/pyhik#1]
I found this awesome Python script that talks to HIKVISION NVR.

Unfortunately, when I run it, it returns error as following:

`Traceback (most recent call last):
  File ".\test.py", line 531, in <module>
    startCapture16("10.78.203.159",8000,"admin","12345",0.0066)
  File ".\test.py", line 499, in startCapture16
    userId,deviceInfo = login(ip,port,username,password,f)
  File ".\test.py", line 258, in login
    _userId = _l(dIP,dPort,username,password,ctypes.byref(_info))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type`

How may I solve it? 

Also, do you have a newer version of pyhik.py?

**Comment by goudam-jm** [comment]
@AhSem which version of Python do you use? I had written and tested this library with Python 2.7

**Comment by AhSem** [comment]
I see. I am using Python 3.6.5. 

Do you have a newer version of pyhik.py that have more functionalities such as getting playback etc?

**Comment by goudam-jm** [comment]
I currently don't have plans for adding more functionalities to the library due to the lack of a hikvision equipment. I, however, can see what can be done about supporting Python 3.
